AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Feedback
      AttributeDefinitions:
        - AttributeName: feedback_id
          AttributeType: S
      KeySchema:
        - AttributeName: feedback_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  SaveFeedbackLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SaveFeedback
      Runtime: python3.9
      Handler: save_feedback.lambda_handler
      Code:
        S3Bucket: my-lambda-code-bucket
        S3Key: save_feedback.zip
      Role: arn:aws:iam::123456789012:role/lambda-role
